In [22]:
import numpy as np

In [ ]:
print('list(a): ', list(a))
print('tolist(): ', a.tolist())

In [33]:
#簡答題
# print(list(a)) #只轉第一層
# print(a.tolist()) #全部都轉list

# list()只能將數據中的最外層的元素轉換成列表
# tolist()將多維的陣列架構轉換為多維的列表

In [25]:
#作業2
a = np.random.randint(10, size=6)

print(a)
print(a.ndim) #維度
print(a.shape) #每個維度的大小
print(a.size) #size
print(a.dtype) #陣列中的資料型態
print(a.itemsize) #每個元素佔用的空間
print(a.data) 

[4 5 0 1 5 0]
1
(6,)
6
int64
8


In [26]:
b = np.random.randint(10, size=(3,4))

print(b)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

[[9 8 7 7]
 [3 5 2 5]
 [8 2 4 5]]
1
(6,)
6
int64
8


In [27]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

[[[9 8]
  [8 7]
  [7 8]]

 [[8 9]
  [3 7]
  [2 6]]]
1
(6,)
6
int64
8


In [34]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[0, 4, 8, 1, 1, 2]
[0, 4, 8, 1, 1, 2]


In [31]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[4, 2, 3, 5], [7, 3, 5, 9], [1, 2, 4, 8]]
[array([4, 2, 3, 5]), array([7, 3, 5, 9]), array([1, 2, 4, 8])]


In [32]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[[[2, 3], [4, 6], [3, 7]], [[5, 1], [4, 7], [8, 1]]]
[array([[2, 3],
       [4, 6],
       [3, 7]]), array([[5, 1],
       [4, 7],
       [8, 1]])]


In [28]:
#作業3
def tolist(*iterable):
    for it in iterable:
        return it.tolist()
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[4, 5, 0, 1, 5, 0]
[[9, 8, 7, 7], [3, 5, 2, 5], [8, 2, 4, 5]]
[[[9, 8], [8, 7], [7, 8]], [[8, 9], [3, 7], [2, 6]]]


In [13]:
np.arange(21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [6]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
np.arange(0,21,3)

array([ 0,  3,  6,  9, 12, 15, 18])